eureka:
    client:
        fetchRegistry: false
        registerWithEureka: false

logging:
    level:
        com:
            netflix:
                discovery: 'OFF'
                eureka: 'OFF'

server:
    port: 8761
